# Generated by Django 4.2.28 on 2026-03-13 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_exam_reminders', models.BooleanField(default=True)),
                ('email_results', models.BooleanField(default=True)),
                ('email_security_alerts', models.BooleanField(default=True)),
                ('inapp_exam_reminders', models.BooleanField(default=True)),
                ('inapp_results', models.BooleanField(default=True)),
                ('inapp_security_alerts', models.BooleanField(default=True)),
                ('disable_until', models.DateTimeField(blank=True, null=True)),
                ('max_notifications_per_hour', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EXAM_REMINDER', 'Exam Reminder'), ('EXAM_STARTED', 'Exam Started'), ('EXAM_ENDING', 'Exam Ending Soon'), ('RESULT_READY', 'Result Available'), ('SECURITY_ALERT', 'Security Alert'), ('ADMIN_MESSAGE', 'Admin Broadcast'), ('CHEATING_DETECTED', 'Cheating Detection')], max_length=20)),
                ('method', models.CharField(choices=[('EMAIL', 'Email'), ('INAPP', 'In-App')], max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'sent_at'], name='notificatio_user_id_c1441d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('EXAM_REMINDER', 'Exam Reminder'), ('EXAM_STARTED', 'Exam Started'), ('EXAM_ENDING', 'Exam Ending Soon'), ('RESULT_READY', 'Result Available'), ('SECURITY_ALERT', 'Security Alert'), ('ADMIN_MESSAGE', 'Admin Broadcast'), ('CHEATING_DETECTED', 'Cheating Detection')], max_length=20)),
                ('related_exam_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
