# Generated by Django 4.2.29 on 2026-03-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_auto_20260219_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_registration',
            name='choice_One',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='admission.choiceone'),
        ),
        migrations.AlterField(
            model_name='applicant_registration',
            name='choice_Three',
            field=models.OneToOneField(default='3', on_delete=django.db.models.deletion.CASCADE, to='admission.choicethree'),
        ),
        migrations.AlterField(
            model_name='applicant_registration',
            name='choice_Two',
            field=models.OneToOneField(default='2', on_delete=django.db.models.deletion.CASCADE, to='admission.choicetwo'),
        ),
    ]
