# Generated by Django 4.2.28 on 2026-03-10 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0036_alter_exam_model_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=questions.models._now_rounded_to_minute),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=questions.models._now_rounded_to_minute),
        ),
        migrations.CreateModel(
            name='FocusLossEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switched Away'), ('WINDOW_BLUR', 'Window Lost Focus'), ('VISIBILITY', 'Page Hidden')], default='TAB_SWITCH', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('browser_timestamp', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_loss_events', to='questions.exam_model')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_loss_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'exam'], name='questions_f_student_9cc78d_idx'), models.Index(fields=['timestamp'], name='questions_f_timesta_19b5cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamSecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('BLOCKED', 'Exam Blocked')], default='WARNING', max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='questions.exam_model')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'exam'], name='questions_e_student_4f8fb2_idx'), models.Index(fields=['level'], name='questions_e_level_a858cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamFocusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_loss_count', models.IntegerField(default=0)),
                ('max_focus_losses', models.IntegerField(default=3)),
                ('last_focus_loss_time', models.DateTimeField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_logs', to='questions.exam_model')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'exam'], name='questions_e_student_6000d7_idx'), models.Index(fields=['created_at'], name='questions_e_created_ecaf30_idx')],
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
