# Generated by Django 4.2.28 on 2026-03-10 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0037_alter_exam_model_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(blank=True, help_text='e.g., CSE-2024-A', max_length=100)),
                ('assignment_type', models.CharField(choices=[('individual', 'Individual Student'), ('batch', 'Entire Batch/Class'), ('public', 'All Students')], default='public', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='questions.exam_model')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Assignment',
                'verbose_name_plural': 'Exam Assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['exam', 'is_active'], name='questions_e_exam_id_b35cac_idx'), models.Index(fields=['student'], name='questions_e_student_d548ae_idx'), models.Index(fields=['batch_name'], name='questions_e_batch_n_7ac0ff_idx')],
                'unique_together': {('exam', 'student', 'batch_name')},
            },
        ),
    ]
