# Generated by Django 4.2.28 on 2026-03-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_examassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_db',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='question_db',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question_db',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='question_db',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionA',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionB',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionC',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionD',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='question_db',
            index=models.Index(fields=['professor', 'difficulty'], name='questions_q_profess_b61dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='question_db',
            index=models.Index(fields=['created_at'], name='questions_q_created_4dc83b_idx'),
        ),
    ]
