# Generated by Django 4.2.29 on 2026-03-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0039_alter_question_db_options_question_db_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
