# Generated by Django 6.0.3 on 2026-03-22 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0042_alter_examfocuslog_max_focus_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='optionA_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='question_db',
            name='optionB_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='question_db',
            name='optionC_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='question_db',
            name='optionD_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='question_db',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionA',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionB',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionC',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionD',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
